server:
  port: 8094
spring:
  datasource:
    url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/XXX?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: XXX
    password: XXX
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 64
      idle-timeout: 25000
      auto-commit: true
      connection-test-query: select 1
  redis:
    redisson:
      config: classpath:redisson/redisson-prod.yml
logging:
  config: classpath:logback/logback-prod.xml

open:
  aes:
    skey: 8cb22b6023f2773a
