# å¼€å‘ç¯å¢ƒé…ç½®
#ç³»ç»Ÿæˆæƒ
system:
  auth:
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJiDIHPpNB8mD1R9bKaEeUVI7Cj6LkOuTSGY73ZFUygpehLxKZyWO98RvX0Jf5Qdwe7OkcH6WTEC9ryZPvyTerrmDE05NPxkoek/epnGjdPrnANh8emq2IVzVW//WUnoKe44Ho4yeaAvnbZr3mlIxtNvgae3AMKV7d+X3FUS3r5jAgMBAAECgYAFSrd7jiHy2r05b0iv1nTmxIr9OQEV9BxVCBt2/RzPjfDga2HIPyZArTrn9cZpe0bZZG2GT4t8ud+Z169p0Cw39kD6k1IJUnFZQB2E5hfjUQEVDMi2vJ6yFoMtsIu3tsGfhg28E98f0gZhRF/vN47CGX3docXHgASeG5UNV9tJIQJBAMeDAsDxeSEDtHYuTVLyXTmfS3uONFQDrVJJZZ5tteOii0RsjIVpjfHtSK1gNCVUr2BOJI0YM2VMTfBW9+vb+ysCQQDDsYAF0Q/uby7+H2D79kRisCjxOTVNNrTee+tWoT+IF+dg+n3HuIVj8VpLwR/OVyk1tNlwOQVrKGwH+z2HTk2pAkEAiSZqsjBNUIC3gbZ6uVaa942l2h37ovWUJEkIbkyFCSMoEbV9NAlH5tNzbpv/vNnmZZHSVpwYWL6HpXxjmePzWQJAMGo7uDSu8liDkc+FmRCmfpwCpRt4OnAsc1bJNJeUNkFjtzSB5eWa6s0Nf+x5x/z8bxMdMIyK8KYBhD/+SvlucQJAI5JCqvaTqDx462am1+Pe1Apwh4ITA4luVJijTsqzibxw1BlhxM+YmoucVky14nDXnCuy4PeZ3SXRan2M5/+yug==

# é¡¹ç›®ç›¸å…³é…ç½®
zhongkang:
  # åç§°
  name: æ²ƒå¾·å¥ç®¡äº‘å¹³å°
  # ç‰ˆæœ¬
  version: V2.6.1
  # ç‰ˆæƒå¹´ä»½
  copyrightYear: 2022
  # å®ä¾‹æ¼”ç¤ºå¼€å…³
  demoEnabled: true
  # æ–‡ä»¶è·¯å¾„ ç¤ºä¾‹ï¼ˆ Windowsé…ç½®D:/newmecï¼ŒLinuxé…ç½® /www/nasï¼‰
  profile: D:/newmec
  profileLinux: /www/nas
  # è·å–ipåœ°å€å¼€å…³
  addressEnabled: false
  # éªŒè¯ç ç±»å‹ math æ•°ç»„è®¡ç®— char å­—ç¬¦éªŒè¯
  captchaType: math
  #æ˜¯å¦çº¿ä¸Šç³»ç»Ÿ
  online: false

server:
  # æœåŠ¡å™¨çš„HTTPç«¯å£ï¼Œé»˜è®¤ä¸º8080
  port: 8090
  servlet:
    # åº”ç”¨çš„è®¿é—®è·¯å¾„
    context-path: /
  tomcat:
    # tomcatçš„URIç¼–ç 
    uri-encoding: UTF-8
    # è¿æ¥æ•°æ»¡åçš„æ’é˜Ÿæ•°ï¼Œé»˜è®¤ä¸º100
    accept-count: 1000
    threads:
      # tomcatæœ€å¤§çº¿ç¨‹æ•°ï¼Œé»˜è®¤ä¸º200
      max: 800
      # Tomcatå¯åŠ¨åˆå§‹åŒ–çš„çº¿ç¨‹æ•°ï¼Œé»˜è®¤å€¼10
      min-spare: 100
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # ğŸ‘‡ å¼€å¯å›æ”¶æœºåˆ¶
      removeAbandoned: true
      # ğŸ‘‡ è¶…æ—¶æ—¶é—´ï¼ˆå•ä½ç§’ï¼‰ï¼šäº‹åŠ¡/è¿æ¥è¶…è¿‡ 5 åˆ†é’Ÿæœªå…³é—­å°±å›æ”¶
      removeAbandonedTimeout: 50
      # ğŸ‘‡ å¼€å¯æ—¥å¿—ï¼Œæ’æŸ¥æ³„éœ²æº
      logAbandoned: true
      # ä¸»åº“æ•°æ®æº
      master:
      url: jdbc:mysql://XXX.XXX.XXX.XXX:38306/XXX?sessionVariables=group_concat_max_len=10000&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&tinyInt1isBit=false&transformedBitIsBoolean=false
      username: XXX
      password: XXX
      slave:
        # ä»æ•°æ®æºå¼€å…³/é»˜è®¤å…³é—­
        enabled: false
        driver-class-name: oracle.jdbc.OracleDriver
        url:
        username:
        password:
      applet:
        # ä»æ•°æ®æºå¼€å…³/é»˜è®¤å…³é—­
        enabled: false
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:
        username:
        password:
      # åˆå§‹è¿æ¥æ•°
      initialSize: 5
      # æœ€å°è¿æ¥æ± æ•°é‡
      minIdle: 10
      # æœ€å¤§è¿æ¥æ± æ•°é‡
      maxActive: 20
      # é…ç½®è·å–è¿æ¥ç­‰å¾…è¶…æ—¶çš„æ—¶é—´
      maxWait: 60000
      # é…ç½®é—´éš”å¤šä¹…æ‰è¿›è¡Œä¸€æ¬¡æ£€æµ‹ï¼Œæ£€æµ‹éœ€è¦å…³é—­çš„ç©ºé—²è¿æ¥ï¼Œå•ä½æ˜¯æ¯«ç§’
      timeBetweenEvictionRunsMillis: 60000
      # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å°ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½æ˜¯æ¯«ç§’
      minEvictableIdleTimeMillis: 300000
      # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å¤§ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½æ˜¯æ¯«ç§’
      maxEvictableIdleTimeMillis: 900000
      # é…ç½®æ£€æµ‹è¿æ¥æ˜¯å¦æœ‰æ•ˆ
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # è®¾ç½®ç™½åå•ï¼Œä¸å¡«åˆ™å…è®¸æ‰€æœ‰è®¿é—®
        allow:
        url-pattern: /druid/*
        # æ§åˆ¶å°ç®¡ç†ç”¨æˆ·åå’Œå¯†ç 
        login-username: world
        login-password: 123456
      filter:
        stat:
          enabled: true
          # æ…¢SQLè®°å½•
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    redisson:
      config: classpath:redisson/redisson-dev.yml
  # RabbitMQ é…ç½®
  rabbitmq:
    host:
    port:
    username:
    password:
    # ç¦æ­¢è‡ªåŠ¨å¯åŠ¨è¿æ¥
    listener:
      simple:
        auto-startup: false
# æ—¥å¿—é…ç½®
logging:
  level:
    com.center.medical: debug
    org.springframework: warn
  config: classpath:logback/logback-dev.xml

#é€šç”¨AESåŠ å¯†å¯†é’¥
open:
  aes:
    skey: 146604D44F7E91CE

#çº¿ä¸Šçº¿ä¸‹æ•°æ®åŒæ­¥ç›¸å…³çš„é…ç½®
sync:
  open: 0 #æ˜¯å¦å¼€å¯åŒæ­¥åŠŸèƒ½ï¼š0.å…³é—­ 1.å¼€å¯
  amq:
    online:
      queue:
        data: "pfSyncDataQueue" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯é˜Ÿåˆ—
        file: "pfSyncFileQueue" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯é˜Ÿåˆ—
        file2: "lcSyncFileQueue" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯é˜Ÿåˆ—
      topicExchange:
        data: "pf.sync.data.topic" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯äº¤æ¢æœº
        file: "pf.sync.file.topic" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯äº¤æ¢æœº
        file2: "lc.sync.file.topic" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯äº¤æ¢æœº
      routingKey:
        data: "pfSyncDataRoutingKey" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯è·¯ç”±
        file: "pfSyncFileRoutingKey" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯è·¯ç”±
        file2: "lcSyncFileRoutingKey" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯è·¯ç”±
    offline:
      queue:
        data:
        file1:
        file2:
      topicExchange:
        data:
        file1:
        file2:
      routingKey:
        data:
        file1:
        file2:

#æ¶ˆæ¯é˜Ÿåˆ—é…ç½®ï¼Œptlï¼šçº¿ä¸Šåˆ°çº¿ä¸‹ï¼Œltpï¼šçº¿ä¸‹åˆ°çº¿ä¸Š
rabbitmq:
  online:
    queue:
      request: "ltpRequestQueue" #æ¥æ”¶çº¿ä¸‹è¯·æ±‚çš„æ¶ˆæ¯é˜Ÿåˆ—
    topicExchange:
      request: "ltp.request.topic" #æ¥æ”¶çº¿ä¸‹è¯·æ±‚çš„æ¶ˆæ¯äº¤æ¢æœº
    routingKey:
      request: "ltpRequestRoutingKey" #æ¥æ”¶çº¿ä¸‹è¯·æ±‚çš„æ¶ˆæ¯è·¯ç”±
  offline:
    queue:
      request: "ptlRequestQueue" #æ¥æ”¶çº¿ä¸Šå‘å½“å‰åˆ†ä¸­å¿ƒå‘é€è¯·æ±‚çš„æ¶ˆæ¯é˜Ÿåˆ—
    topicExchange:
      request: "ptl.request.topic" #æ¥æ”¶çº¿ä¸Šå‘å½“å‰åˆ†ä¸­å¿ƒå‘é€è¯·æ±‚çš„æ¶ˆæ¯äº¤æ¢æœº
    routingKey:
      request: "ptlRequestRoutingKey" #æ¥æ”¶çº¿ä¸Šå‘å½“å‰åˆ†ä¸­å¿ƒå‘é€è¯·æ±‚çš„æ¶ˆæ¯è·¯ç”±
#elastic:
#  address: http://localhost:9200
