#预约小程序配置
wx:
  xcx:
    appId: wx7affad25284aeedb
    appSecret: 6eaf7d86d867b17a6e501a11a990025a

#通用AES加密密钥
open:
  aes:
    skey: 146604D44F7E91CE

#系统授权
system:
  auth:
    privateKey:

#dicom图片
dicom:
  ip:
  port:
  callingAET:
  mianApiUrl:
  fileRoot:
  fileRootLinux: # Linux系统下dcm图片存储的根目录

# RabbitMQ 配置
spring:
  rabbitmq:
    host:
    port:
    username:
    password:

#线上线下数据同步相关的配置
sync:
  open: 0 #是否开启同步功能：0.关闭 1.开启
  amq:
    online:
      queue:
        data:
        file:
        file2:
      topicExchange:
        data:
        file:
        file2:
      routingKey:
        data:
        file:
        file2:
    offline:
      queue:
        data:
        file1:
        file2:
      topicExchange:
        data:
        file1:
        file2:
      routingKey:
        data:
        file1:
        file2: