# å¼€å‘ç¯å¢ƒé…ç½®
#ç³»ç»Ÿæˆæƒ
system:
  auth:
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAPBMxXx8okltQUcWQUcr6FPeNdKP5NjwP+EX7ihDCQBwqiN4aQAd52QaDILZYqD7wvh9obEXGlQ9i/ro4H+Z4nv3rdaohXLrgLR1nvaL6Uz+4kqdbqNPcGxS8dxTTePlDt96PKXsBR650nQ74ac2FskwxeUKmZcCIiirQbK689AfAgMBAAECgYBQFTXHm/21vMyBdWBB6NcfhDGpv7zDs6WGTaRYFKceV23MLmfH2y9vQ+MhhHMDNYQvribBzvI+WtiYwR14SP+aLYefHxnSDZy1GhtwZentiPNz3FuOgG/0EQeSnrlcKuFIckZFIQVLFmQn2RQlGw2P0Hcj/gjvJmnD/R+26pV0OQJBAPr5lltkcerUyhqSObD5rW3fmwf22bUOw5Djni5nI/zZrhoXz5MfvyPiuPoQ74fcZO8qJVhA4fClvK1+tRU1aJsCQQD1HHejxZPl1UVQOZCdoYhBMKt71Du4Mc7RChX7+LslPvDkMmTTQlH7MSTceZe0Aq7TUEh9xEH5mXZCnWCd3+TNAkEArGG+CmwFarxZTMLe6VW072DEhUXh5uCLJvuQbGLfbw687KMqKe2GRcm2L9xuCa0xjqwuFl4KUlYkMC51hmm2vQJBALT97VYwSfKXlhQUPbY4Fg3VK3tHj0WG+emf4fXqh/6LyIMotwzMVw7+DfMDkkKpDIEbMjw0FGeDqzCrVzGcpy0CQCMjSdshZXw75YfWGTITQYdTcBsl4uF55sp10ys9o7UvvrotuDCsgTqXJRbHb6tLMCD0H9t8cjRcnl2hAm4JDU8=

project:
  name: admin
  online: 0
# é¡¹ç›®ç›¸å…³é…ç½®
zhongkang:
  # åç§°
  name: æ²ƒå¾·å¥ç®¡äº‘å¹³å°
  # ç‰ˆæœ¬
  version: V2.6.1
  # ç‰ˆæƒå¹´ä»½
  copyrightYear: 2022
  # å®ä¾‹æ¼”ç¤ºå¼€å…³
  demoEnabled: true
  # æ–‡ä»¶è·¯å¾„ ç¤ºä¾‹ï¼ˆ Windowsé…ç½®D:/newmecï¼ŒLinuxé…ç½® /www/nasï¼‰
  profile: D:\image
  profileLinux: /www/nas
  # è·å–ipåœ°å€å¼€å…³
  addressEnabled: false
  # éªŒè¯ç ç±»å‹ math æ•°ç»„è®¡ç®— char å­—ç¬¦éªŒè¯
  captchaType: math
  #æ˜¯å¦çº¿ä¸Šç³»ç»Ÿ
  online: false
  #åˆ†ä¸­å¿ƒID
  fzxId: 2
  #åˆ†ä¸­å¿ƒç®€ç 
  fzxjm: "01"

server:
  # æœåŠ¡å™¨çš„HTTPç«¯å£ï¼Œé»˜è®¤ä¸º8080
  port: 8080
  servlet:
    # åº”ç”¨çš„è®¿é—®è·¯å¾„
    context-path: /
  tomcat:
    # tomcatçš„URIç¼–ç 
    uri-encoding: UTF-8
    # è¿æ¥æ•°æ»¡åçš„æ’é˜Ÿæ•°ï¼Œé»˜è®¤ä¸º100
    accept-count: 1000
    threads:
      # tomcatæœ€å¤§çº¿ç¨‹æ•°ï¼Œé»˜è®¤ä¸º200
      max: 800
      # Tomcatå¯åŠ¨åˆå§‹åŒ–çš„çº¿ç¨‹æ•°ï¼Œé»˜è®¤å€¼10
      min-spare: 100
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # ğŸ‘‡ å¼€å¯å›æ”¶æœºåˆ¶
      removeAbandoned: true
      # ğŸ‘‡ è¶…æ—¶æ—¶é—´ï¼ˆå•ä½ç§’ï¼‰ï¼šäº‹åŠ¡/è¿æ¥è¶…è¿‡ 5 åˆ†é’Ÿæœªå…³é—­å°±å›æ”¶
      removeAbandonedTimeout: 50
      # ğŸ‘‡ å¼€å¯æ—¥å¿—ï¼Œæ’æŸ¥æ³„éœ²æº
      logAbandoned: true
      # ä¸»åº“æ•°æ®æº
      master:
        url: jdbc:mysql://61.172.179.73:41002/medical_prod?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&tinyInt1isBit=false&transformedBitIsBoolean=false
        username: root
        password: xZ_TTSL123
      # ä»åº“æ•°æ®æº
      slave:
        # ä»æ•°æ®æºå¼€å…³/é»˜è®¤å…³é—­
        enabled: false
        driver-class-name: oracle.jdbc.OracleDriver
        url:
        username:
        password:
      # åˆå§‹è¿æ¥æ•°
      initialSize: 5
      # æœ€å°è¿æ¥æ± æ•°é‡
      minIdle: 10
      # æœ€å¤§è¿æ¥æ± æ•°é‡
      maxActive: 20
      # é…ç½®è·å–è¿æ¥ç­‰å¾…è¶…æ—¶çš„æ—¶é—´
      maxWait: 60000
      # é…ç½®é—´éš”å¤šä¹…æ‰è¿›è¡Œä¸€æ¬¡æ£€æµ‹ï¼Œæ£€æµ‹éœ€è¦å…³é—­çš„ç©ºé—²è¿æ¥ï¼Œå•ä½æ˜¯æ¯«ç§’
      timeBetweenEvictionRunsMillis: 60000
      # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å°ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½æ˜¯æ¯«ç§’
      minEvictableIdleTimeMillis: 300000
      # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å¤§ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½æ˜¯æ¯«ç§’
      maxEvictableIdleTimeMillis: 900000
      # é…ç½®æ£€æµ‹è¿æ¥æ˜¯å¦æœ‰æ•ˆ
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # è®¾ç½®ç™½åå•ï¼Œä¸å¡«åˆ™å…è®¸æ‰€æœ‰è®¿é—®
        allow:
        url-pattern: /druid/*
        # æ§åˆ¶å°ç®¡ç†ç”¨æˆ·åå’Œå¯†ç 
        login-username: world
        login-password: 123456
      filter:
        stat:
          enabled: true
          # æ…¢SQLè®°å½•
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    redisson:
      config: classpath:redisson/redisson-dev.yml
  # RabbitMQ é…ç½®
  rabbitmq:
    host:
    port:
    username:
    password:
    # ç¦æ­¢è‡ªåŠ¨å¯åŠ¨è¿æ¥
    listener:
      simple:
        auto-startup: false
logging:
  level:
    com.center.medical: debug
    org.springframework: warn
  config: classpath:logback/logback-dev.xml

#é€šç”¨AESåŠ å¯†å¯†é’¥
open:
  aes:
    skey: 146604D44F7E91CE

#çº¿ä¸Šçº¿ä¸‹æ•°æ®åŒæ­¥ç›¸å…³çš„é…ç½®
sync:
  open: 0 #æ˜¯å¦å¼€å¯åŒæ­¥åŠŸèƒ½ï¼š0.å…³é—­ 1.å¼€å¯
  amq:
    online:
      queue:
        data: "pfSyncDataQueue" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯é˜Ÿåˆ—
        file: "pfSyncFileQueue" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯é˜Ÿåˆ—
        file2: "lcSyncFileQueue" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯é˜Ÿåˆ—
      topicExchange:
        data: "pf.sync.data.topic" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯äº¤æ¢æœº
        file: "pf.sync.file.topic" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯äº¤æ¢æœº
        file2: "lc.sync.file.topic" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯äº¤æ¢æœº
      routingKey:
        data: "pfSyncDataRoutingKey" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯è·¯ç”±
        file: "pfSyncFileRoutingKey" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯è·¯ç”±
        file2: "lcSyncFileRoutingKey" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯è·¯ç”±
    offline:
      queue:
        data: "pfSyncDataQueue01" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯é˜Ÿåˆ—
        file1: "pfSyncFileQueue01" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯é˜Ÿåˆ—
        file2: "lcSyncFileQueue01" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯é˜Ÿåˆ—
      topicExchange:
        data: "pf.sync.data.topic.01" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯äº¤æ¢æœº
        file1: "pf.sync.file.topic.01" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯äº¤æ¢æœº
        file2: "lc.sync.file.topic.01" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯äº¤æ¢æœº
      routingKey:
        data: "pfSyncDataRoutingKey01" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ•°æ®çš„æ¶ˆæ¯è·¯ç”±
        file1: "pfSyncFileRoutingKey01" #çº¿ä¸ŠåŒæ­¥åˆ°å½“å‰åˆ†ä¸­å¿ƒçš„æ–‡ä»¶çš„æ¶ˆæ¯è·¯ç”±
        file2: "lcSyncFileRoutingKey01" #å½“å‰åˆ†ä¸­å¿ƒåŒæ­¥åˆ°çº¿ä¸Šçš„æ–‡ä»¶çš„æ¶ˆæ¯è·¯ç”±

#æ¶ˆæ¯é˜Ÿåˆ—é…ç½®ï¼Œptlï¼šçº¿ä¸Šåˆ°çº¿ä¸‹ï¼Œltpï¼šçº¿ä¸‹åˆ°çº¿ä¸Š
rabbitmq:
  online:
    queue:
      request: "ltpRequestQueue" #æ¥æ”¶çº¿ä¸‹è¯·æ±‚çš„æ¶ˆæ¯é˜Ÿåˆ—
    topicExchange:
      request: "ltp.request.topic" #æ¥æ”¶çº¿ä¸‹è¯·æ±‚çš„æ¶ˆæ¯äº¤æ¢æœº
    routingKey:
      request: "ltpRequestRoutingKey" #æ¥æ”¶çº¿ä¸‹è¯·æ±‚çš„æ¶ˆæ¯è·¯ç”±
  offline:
    queue:
      request: "ptlRequestQueue01" #æ¥æ”¶çº¿ä¸Šå‘å½“å‰åˆ†ä¸­å¿ƒå‘é€è¯·æ±‚çš„æ¶ˆæ¯é˜Ÿåˆ—
    topicExchange:
      request: "ptl.request.topic.01" #æ¥æ”¶çº¿ä¸Šå‘å½“å‰åˆ†ä¸­å¿ƒå‘é€è¯·æ±‚çš„æ¶ˆæ¯äº¤æ¢æœº
    routingKey:
      request: "ptlRequestRoutingKey01" #æ¥æ”¶çº¿ä¸Šå‘å½“å‰åˆ†ä¸­å¿ƒå‘é€è¯·æ±‚çš„æ¶ˆæ¯è·¯ç”±

#elastic:
#  address: http://localhost:9200
