system:
  auth:
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAPBMxXx8okltQUcWQUcr6FPeNdKP5NjwP+EX7ihDCQBwqiN4aQAd52QaDILZYqD7wvh9obEXGlQ9i/ro4H+Z4nv3rdaohXLrgLR1nvaL6Uz+4kqdbqNPcGxS8dxTTePlDt96PKXsBR650nQ74ac2FskwxeUKmZcCIiirQbK689AfAgMBAAECgYBQFTXHm/21vMyBdWBB6NcfhDGpv7zDs6WGTaRYFKceV23MLmfH2y9vQ+MhhHMDNYQvribBzvI+WtiYwR14SP+aLYefHxnSDZy1GhtwZentiPNz3FuOgG/0EQeSnrlcKuFIckZFIQVLFmQn2RQlGw2P0Hcj/gjvJmnD/R+26pV0OQJBAPr5lltkcerUyhqSObD5rW3fmwf22bUOw5Djni5nI/zZrhoXz5MfvyPiuPoQ74fcZO8qJVhA4fClvK1+tRU1aJsCQQD1HHejxZPl1UVQOZCdoYhBMKt71Du4Mc7RChX7+LslPvDkMmTTQlH7MSTceZe0Aq7TUEh9xEH5mXZCnWCd3+TNAkEArGG+CmwFarxZTMLe6VW072DEhUXh5uCLJvuQbGLfbw687KMqKe2GRcm2L9xuCa0xjqwuFl4KUlYkMC51hmm2vQJBALT97VYwSfKXlhQUPbY4Fg3VK3tHj0WG+emf4fXqh/6LyIMotwzMVw7+DfMDkkKpDIEbMjw0FGeDqzCrVzGcpy0CQCMjSdshZXw75YfWGTITQYdTcBsl4uF55sp10ys9o7UvvrotuDCsgTqXJRbHb6tLMCD0H9t8cjRcnl2hAm4JDU8=

#线上线下数据同步相关的配置
sync:
  open: 0 #是否开启同步功能：0.关闭 1.开启
  amq:
    online:
      queue:
        data:
        file:
        file2:
      topicExchange:
        data:
        file:
        file2:
      routingKey:
        data:
        file:
        file2:
    offline:
      queue:
        data:
        file1:
        file2:
      topicExchange:
        data:
        file1:
        file2:
      routingKey:
        data:
        file1:
        file2:
project:
  name: datamove
# 日志配置
logging:
  level:
    com.center.medical: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #当出现相同名字的类进行注册时，准许覆盖注册
  main:
    allow-bean-definition-overriding: true
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认2个小时）
  expireTime: 7200

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 用于雪花算法生成id
application:
  datacenterId: 2
  workerId: 1

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

knife4j:
  enable: true
  # 生产环境屏蔽
  # production: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: only
    password: only
  documents:
    - group: 2.X版本
      name: 另外文档分组请看这里
      locations: classpath:markdown/*
    - group: 2.X版本
      name: 接入方法
      locations: classpath:markdown/api.md

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#spring boot actuator配置
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown,info

#预约小程序配置
wx:
  xcx:
    appId:
    appSecret: