# æ­£å¼ç¯å¢ƒé…ç½®

# é¡¹ç›®ç›¸å…³é…ç½®
zhongkang:
  # åç§°
  name: æ²ƒå¾·å¥ç®¡äº‘å¹³å°
  # ç‰ˆæœ¬
  version: V2.6.1
  # ç‰ˆæƒå¹´ä»½
  copyrightYear: 2022
  # å®ä¾‹æ¼”ç¤ºå¼€å…³
  demoEnabled: true
  # æ–‡ä»¶è·¯å¾„ ç¤ºä¾‹ï¼ˆ Windowsé…ç½®D:/zhongkang/files/uploadPathï¼ŒLinuxé…ç½® /newimageï¼‰
  profile: /www/nas
  profileLinux: /www/nas
  # è·å–ipåœ°å€å¼€å…³
  addressEnabled: false
  # éªŒè¯ç ç±»å‹ math æ•°ç»„è®¡ç®— char å­—ç¬¦éªŒè¯
  captchaType: math
  #æ˜¯å¦çº¿ä¸Šç³»ç»Ÿ
  online: false
  #åˆ†ä¸­å¿ƒID
  fzxId:
  #åˆ†ä¸­å¿ƒç®€ç 
  fzxjm:

server:
  port: 8082
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # ğŸ‘‡ å¼€å¯å›æ”¶æœºåˆ¶
      removeAbandoned: true
      # ğŸ‘‡ è¶…æ—¶æ—¶é—´ï¼ˆå•ä½ç§’ï¼‰ï¼šäº‹åŠ¡/è¿æ¥è¶…è¿‡ 5 åˆ†é’Ÿæœªå…³é—­å°±å›æ”¶
      removeAbandonedTimeout: 50
      # ğŸ‘‡ å¼€å¯æ—¥å¿—ï¼Œæ’æŸ¥æ³„éœ²æº
      logAbandoned: true
      # ä¸»åº“æ•°æ®æº
      master:
        url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/XXX?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&tinyInt1isBit=false&transformedBitIsBoolean=false
        username: XXX
        password: XXX
      # ä»åº“æ•°æ®æº
      slave:
        # ä»æ•°æ®æºå¼€å…³/é»˜è®¤å…³é—­
        enabled: false
        url:
        username:
        password:
      # åˆå§‹è¿æ¥æ•°
      initialSize: 5
      # æœ€å°è¿æ¥æ± æ•°é‡
      minIdle: 10
      # æœ€å¤§è¿æ¥æ± æ•°é‡
      maxActive: 20
      # é…ç½®è·å–è¿æ¥ç­‰å¾…è¶…æ—¶çš„æ—¶é—´
      maxWait: 60000
      # é…ç½®é—´éš”å¤šä¹…æ‰è¿›è¡Œä¸€æ¬¡æ£€æµ‹ï¼Œæ£€æµ‹éœ€è¦å…³é—­çš„ç©ºé—²è¿æ¥ï¼Œå•ä½æ˜¯æ¯«ç§’
      timeBetweenEvictionRunsMillis: 60000
      # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å°ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½æ˜¯æ¯«ç§’
      minEvictableIdleTimeMillis: 300000
      # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å¤§ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½æ˜¯æ¯«ç§’
      maxEvictableIdleTimeMillis: 900000
      # é…ç½®æ£€æµ‹è¿æ¥æ˜¯å¦æœ‰æ•ˆ
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # è®¾ç½®ç™½åå•ï¼Œä¸å¡«åˆ™å…è®¸æ‰€æœ‰è®¿é—®
        allow:
        url-pattern: /druid/*
        # æ§åˆ¶å°ç®¡ç†ç”¨æˆ·åå’Œå¯†ç 
        login-username: world
        login-password: 123456
      filter:
        stat:
          enabled: true
          # æ…¢SQLè®°å½•
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    redisson:
      config: classpath:redisson/redisson-prod.yml
logging:
  config: classpath:logback/logback-prod.xml
#elastic:
#  address: http://localhost:9200
