project:
  name: deploy

# 日志配置
logging:
  level:
    com.center.medical: debug
    org.springframework: warn

spring:
  profiles:
    active: dev

#spring boot actuator配置
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown,info